#!/bin/bash

# Get random image file name
IMG_NAME=$(ls /home/obsy/.config/hypr/wallpapers | shuf -n 1)
# full path to that random image file
IMG_PATH=/home/obsy/.config/hypr/wallpapers/$IMG_NAME
# Command to change wallpaper
swww img $IMG_PATH --transition-type center --transition-fps 60 --transition-speed 16
