#!/bin/bash

# Get random image file name
IMG_NAME=$(ls /home/obsy/Pictures/walls/selected | shuf -n 1)
# full path to that random image file
IMG_PATH_FULL=/home/obsy/Pictures/walls/selected/$IMG_NAME
# Command to change wallpaper
swww img $IMG_PATH_FULL --transition-type grow --transition-fps 60 --transition-duration 1.7 --transition-bezier .73,.095,.3,1
