#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# waybar
$scripts/launch_waybar &

# initiate wallpaper daemon
swww init
#change wallpaper hourly from playlist
$scripts/cycle_wall &	

# effects and notification daemon
$scripts/rgb &
dunst &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

hyprctl switchxkblayout "rk-keyboard-5.1" next

