#!/bin/bash

ROFI_THEME="$HOME/.config/rofi/launchers/type-2/roficritty.rasi"
ALACRITTY_PATH="$HOME/.config/alacritty/alacritty.yml"
SELECTED_SCHEME=$(rofi -dmenu -i -only-match -no-custom -input /home/obsy/.local/bin/list.txt -theme $ROFI_THEME)
if [[ -z $SELECTED_SCHEME ]]
then
echo "Something went wrong 😭" 
else
sed -i "1719 s/.*/colors: *$SELECTED_SCHEME/" $ALACRITTY_PATH
fi